### PR TITLE
Feedback form & minor issues

### PR DESCRIPTION
**Pull request by dLobatog**
What I do in this commit is:
- Complete refactor of method 'create' of issue_controller.rb
- Fix a typo in the homepage text ("can" is repeated twice).
- README with information about the project
- Make the feedback form look like Register/Sign In forms so it matches the look of the website.

Disclaimer - I checked with Bill and it's ok that I contribute even if I am no longer in the team

### CODE REVIEW

**Comment by duyetln** [comment]
Cool, thank Daniel!

**Comment by dLobatog** [comment]
You're welcome, can you merge this? haha

**Comment by dLobatog** [comment]
I added more commits - I commented each of them but basically I did a deep refactor of the method "create" from issue_controller.rb

**Comment by dLobatog** [comment]
Last commit - Just got rid of the gigantic set of ifs and refactored it with a dictionary

**Comment by duyetln** [comment]
I'll merge as soon as we need to deploy a new version. Btw, did you drop the compiler class? I haven't seen you in class lately.

**Comment by dLobatog** [comment]
Lol nope, I just missed ONE class last week + discussion because I already finished the project

**Comment by rgoraya** [comment]
thanks for the checkin Daniel!

2011/12/3 Daniel Lobato Garca <
reply@reply.github.com

> What I do in this commit is:
> - Fix a typo in the homepage text ("can" is repeated twice).
> - README with information about the project
> - Make the feedback form look like Register/Sign In forms so it matches
>   the look of the website.
> 
> Disclaimer - I checked with Bill and it's ok that I contribute even if I
> am no longer in the team
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/eLobato/wc_master master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/rgoraya/wc_master/pull/26
> 
> -- Commit Summary --
> - Changed README to explain what the project does instead of default
>   message
> - Fixed typo in homepage
> - Prettied feedback form to match Register/Sign in and the rest of the
>   forms. Removed .project from RadRails
> 
> -- File Changes --
> 
> D .project (24)
> M README (261)
> M app/views/feed_backs/_form.html.haml (114)
> M app/views/feed_backs/new.html.haml (2)
> M app/views/pages/home.html.haml (2)
> M app/views/user_sessions/_form.html.haml (22)
> M app/views/users/_form.html.haml (1)
> 
> -- Patch Links --
> 
>  https://github.com/rgoraya/wc_master/pull/26.patch
>  https://github.com/rgoraya/wc_master/pull/26.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rgoraya/wc_master/pull/26

## 

Sincere Thanks!

Goraya Raminder Singh
Bren School of Information and Computer Sciences
University of California, Irvine
Irvine, CA 92697-3425rgoraya@uci.edu

**Comment by duyetln** [comment]
Daniel, would you mind using the ruby1.8.7 syntax in the code? I've noticed that you've used some ruby1.9 syntax and that causes some deployment troubles since the system uses ruby1.8.7. Updating to ruby1.9 is too inconvenient now (but I might upgrade ruby in the future).

**Comment by dLobatog** [comment]
Honestly I don't know what part is exclusively 1.9 :( Could you point it out and I will change it?

**Comment by duyetln** [comment]
Haha, I don't even know either. :) I only changed the hash syntax in the issue controller to be compliant with ruby1.8.7. I guess this post answers our problem: http://stackoverflow.com/questions/505983/what-are-the-main-syntax-changes-in-ruby-1-9

**Comment by dLobatog** [comment]
Alrite so that was the only part that did not comply with 1.8.7? Does it work correctly now?

**Pull request merged**
